#!/bin/sh

set -u
set -e

export PATH="${PATH}:/bin:/usr/bin:/usr/local/bin:/usr/pkg/bin"

_log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}
target="${HOME}/git/biggest_list"
rm "${target}/list."*".txt"
anime="/anime/all"
cd "${anime}"
for i in *; do
  [ "${i}" = "all" ] && continue
  _log "Generating list for ${i}..."
  find "$i" -type f | LC_ALL=C sort > "${target}/list.${i}.txt"
done
_log "Done. Sleeping for 5 seconds before continuing..."
sleep 5
_log "Updating repository..."
_log "Start git output"
if cd "${target}"; then
  git add -A
  git commit -m "Auto-updater." || true
  git push
  _log "Done"
else
  _log "Failed"
fi
_log "End git output"
