#!/bin/sh
export PATH=/bin:/usr/bin:/usr/local/bin

_log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}
target="${HOME}/hg/biggest_list"
anime="/anime/all"
cd "${anime}"
for i in *; do
  [ "${i}" = "all" ] && continue
  _log "Generating list for ${i}..."
  find "$i" -type f | sort > "${target}/list.${i}.txt"
done
_log "Done. Sleeping for 5 seconds before continuing..."
sleep 5
_log "Updating repository..."
if cd "${target}"; then
  hg addremove
  hg ci -m "Auto-updater."
  hg push
  _log "Done"
else
  _log "Failed"
fi
