#!/bin/sh

set -u
set -e

export PATH=/bin:/usr/bin:/usr/local/bin

_log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}
target="${HOME}/hg/biggest_list"
anime="/anime/all"
cd "${anime}"
for i in *; do
  [ "${i}" = "all" ] && continue
  _log "Generating list for ${i}..."
  find "$i" -type f | LC_ALL=C sort > "${target}/list.${i}.txt"
done
_log "Done. Sleeping for 5 seconds before continuing..."
sleep 5
_log "Updating repository..."
if cd "${target}"; then
  hg -q addremove || true
  hg -q ci -m "Auto-updater." || true
  hg -q push || true
  _log "Done"
else
  _log "Failed"
fi
